### PR TITLE
Change test_name's formart to file_path#class#func

### PR DESCRIPTION
**Pull request by ninjinkun**
`nose.util.test_address` works well

### CODE REVIEW

**Comment by shuheiktgw** [comment]
Wait I have not approved this PR...

**Comment by ninjinkun** [comment]
Oh, are you still reviewing?

**Comment by shuheiktgw** [comment]
I'm still reviewing but I found one problem. When a non-existing test is specified it seems the plugin raises an error.

```
$ nosetests tests/dir1/test1.py:aa -v --nocapture --nologcapture --launchable --launchable-build-number 1

Failure: ValueError (No such test aa) ... nose.plugins.launchable: WARNING: An unexpected error occurred while optimizing test execution. Please enable debugging by setting a `LAUNCHABLE_DEBUG=1` environment variable and send the logs to Launchable team. Test execution starts in standard order.
nose.plugins.launchable: WARNING: Traceback (most recent call last):
  File "/Users/shuhei/.anyenv/envs/pyenv/versions/3.8.3/lib/python3.8/site-packages/nose_launchable-0.1.0a0-py3.8.egg/launchable/protecter.py", line 15, in func
    return f(*args, **kwargs)
  File "/Users/shuhei/.anyenv/envs/pyenv/versions/3.8.3/lib/python3.8/site-packages/nose_launchable-0.1.0a0-py3.8.egg/launchable/plugin.py", line 96, in addError
    self._addResult(test, CaseEvent.TEAT_FAILED, self._uploader.enqueue_failure)
  File "/Users/shuhei/.anyenv/envs/pyenv/versions/3.8.3/lib/python3.8/site-packages/nose_launchable-0.1.0a0-py3.8.egg/launchable/plugin.py", line 144, in _addResult
    print(get_test_name(test))
  File "/Users/shuhei/.anyenv/envs/pyenv/versions/3.8.3/lib/python3.8/site-packages/nose_launchable-0.1.0a0-py3.8.egg/launchable/plugin.py", line 140, in get_test_name
    file_path, module, name = test_address(t.test)
TypeError: cannot unpack non-iterable NoneType object
```

**Comment by ninjinkun** [comment]
Got it. I revert this branch, then fix it.

**Comment by shuheiktgw** [comment]
When I move the working directory, the root seems to change too. For example, if I execute `nosetests tests/dir1/test1.py`, the testName is `tests/dir1/test1.py#tests.dir1.test1#func_test1`. But if I move into tests/ and execute  `nosetests dir1/test1.py`, then the testName is `dir1/test1.py#tests.dir1.test1#func_test1`.

I don't know if the path should be always from the repository root or not and I'd like to know your opinion on this problem.

**Comment by shuheiktgw** [comment]
It seems generator tests have the same testName...

```
nosetests dir3/test1.py:test_evens -v --nocapture --nologcapture --launchable --launchable-build-number 1
tests.dir3.test1.test_evens(0, 0) ... dir3/test1.py#tests.dir3.test1#test_evens
nose.plugins.launchable: DEBUG: Adding a test result: test: tests.dir3.test1.test_evens(0, 0), context: <module 'tests.dir3.test1' from '/Users/shuhei/projects/launchableinc/rocket-car/tests/dir3/test1.py'>
ok
tests.dir3.test1.test_evens(1, 1) ... dir3/test1.py#tests.dir3.test1#test_evens
nose.plugins.launchable: DEBUG: Adding a test result: test: tests.dir3.test1.test_evens(1, 1), context: <module 'tests.dir3.test1' from '/Users/shuhei/projects/launchableinc/rocket-car/tests/dir3/test1.py'>
ok
tests.dir3.test1.test_evens(2, 2) ... dir3/test1.py#tests.dir3.test1#test_evens
nose.plugins.launchable: DEBUG: Adding a test result: test: tests.dir3.test1.test_evens(2, 2), context: <module 'tests.dir3.test1' from '/Users/shuhei/projects/launchableinc/rocket-car/tests/dir3/test1.py'>
ok
```

**Comment by shuheiktgw** [comment]
Overall it looks great! 👍 
I found a few minor problems so I hope you would fix them or let me know how you feel about them!

**Pull request merged**
